# Generated by Django 5.2.8 on 2025-11-30 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('IN_IM', models.BooleanField()),
                ('MONTHS_OF_WARDS_LEFT', models.IntegerField()),
                ('VACATION_MONTH_PREFERENCES', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='JobSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('min_year', models.IntegerField()),
                ('max_year', models.IntegerField()),
                ('only_IM', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vacation_type', models.CharField(choices=[('0', 'Zero'), ('2+2', 'Two plus Two'), ('5+2', 'Five plus Two')])),
                ('min_visits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorBlockPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.doctor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.section')),
            ],
        ),
    ]
