# Generated by Django 5.2.8 on 2025-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_jobslot_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_visits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
